# -*- coding: utf-8 -*-
"""me fail engrish lol

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tcZDT88T00mBkdiW0JIYLEs8lSn5WJVH
"""

from google.colab import files
data=files.upload()

import csv
import statistics
import plotly.graph_objects as go
import plotly.figure_factory as ff
import pandas as pd
import random

df=pd.read_csv("sample_1.csv")
data=df["reading_time"].tolist()

population_mean = statistics.mean(data)
population_stdev = statistics.stdev(data)
print("average reading time is", population_mean)
print("standard deviation of reading time is", population_stdev)

import csv
import statistics
import plotly.graph_objects as go
import plotly.figure_factory as ff
import pandas as pd
import random

def random_sets_of_mean(counter):
  dataset=[] 
  for i in range(0,counter):
    random_index=random.randint(0,len(data)-1)
    value=data[random_index]
    dataset.append(value)
  mean=statisitcs.mean(dataset)
  return mean



mean_list = []
for i in range (0,100):
  set_of_means=random_set_of_mean 
  mean_list.append(set_of_means)
  def show_fig (mean_list):
    df= mean_list
    fig = ff.create_distplot([df], ["temp"], show_hist = False)
    fig.show()
  show_fig (mean_list)

std_deviation= statistics.stdev(mean_list)
mean=statistics.mean(mean_list)
print("mean of sampling division",mean)
print("Standard deviation of sampling division",std_deviation)

first_std_deviation_start, first_std_deviation_end = mean-std_deviation, mean+std_deviation
second_std_deviation_start, second_std_deviation_end = mean-(2*std_deviation), mean+(2*std_deviation)
third_std_deviation_start, third_std_deviation_end = mean-(3*std_deviation), mean+(3*std_deviation)
print("std1",first_std_deviation_start, first_std_deviation_end)
print("std2",second_std_deviation_start, second_std_deviation_end)
print("std3",third_std_deviation_start,third_std_deviation_end)

from google.colab import files
data=files.upload()

import csv
import statistics
import plotly.graph_objects as go
import plotly.figure_factory as ff
import pandas as pd
import random

df=pd.read_csv("sample_2.csv")
data=df["reading_time"].tolist()

population_mean = statistics.mean(data)
population_stdev = statistics.stdev(data)
print("average reading time is", population_mean)
print("standard deviation of reading time is", population_stdev)

from google.colab import files
data=files.upload()

import csv
import statistics
import plotly.graph_objects as go
import plotly.figure_factory as ff
import pandas as pd
import random

df=pd.read_csv("sample_1.csv")
data=df["reading_time"].tolist()

population_mean = statistics.mean(data)
population_stdev = statistics.stdev(data)
print("average reading time is", population_mean)
print("standard deviation of reading time is", population_stdev)

def random_sets_of_mean(counter):
  dataset=[] 
  for i in range(0,counter):
    random_index=random.randint(0,len(data)-1)
    value=data[random_index]
    dataset.append(value)
  mean=statisitcs.mean(dataset)
  return mean

mean_list = []
for i in range (0,1000):
  random_set_of_mean = set_of_means 
  set_of_means=random_set_of_mean 
  mean_list.append(set_of_means) 

std_deviation= statistics.stdev(mean_list)
mean=statistics.mean(mean_list)
print("mean of sampling division",mean)
print("Standard deviation of sampling division",std_deviation)

z_score = (mean_list - population_mean)/std_deviation
print("z score is = ", z_score)